experimental-backends = true;

backend = "glx";
vsync = true;
use-damage = false;

fading = false;

fade-delta = 6;

log-level = "warn";

rules: (
    {
        match = "window_type = 'notification' && class_g != 'XScreenSaver'";
        animations = (
            {
                triggers = ["open", "show"];
                preset = "slide-in";
                direction = "right";
                duration = 0.2;
            },
            {
                triggers = ["geometry"];
                preset = "geometry-change"; 
                duration = 0.1;
            },
            {
                triggers = ["close", "hide"];
                preset = "slide-out";
                direction = "right";
                duration = 0.2;
            }
        );
    },
    {
        match = "window_type = 'normal'";
        corner-radius = 12;
        animations = (
            {
                triggers = ["geometry"]; 
                preset = "geometry-change";
                duration = 0.2;
            },
            {
                triggers = ["open", "show"];
                preset = "appear";
                duration = 0.2;
            },
            {
                triggers = ["close", "hide"];
                preset = "disappear";
                duration = 0.2;
            }
        )
    },
    {
        match = "class_g = 'Rofi'";
        corner-radius = 0;
        animations = (
            {
                triggers = ["open", "show"];
                preset = "fly-in";
                duration = 0.2;
            },
            {
                triggers = ["close", "hide"];
                preset = "fly-out";
                duration = 0.2;
            },
       )
    },
    {
        match = "name = 'XScreenSaver'";
        animations = (
            {
                triggers = ["open", "show"];
                preset = "appear";
                duration = 0.2;
            },
            {
                triggers = ["close", "hide"];
                preset = "disappear";
                duration = 0.2;
            }
        );
    },
    {
        match = "window_type = 'utility' && class_g = 'awesome'";
        animations = (
            {
                triggers = ["open", "show"];
                preset = "appear";
                duration = 0.2;
            },
            {
                triggers = ["close", "hide"];
                preset = "disappear";
                duration = 0.2;
            }
        );
    },
)
