#!/usr/bin/sh

killall -q sxhkd
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 0.5; done
sxhkd &

polybar-launch
wallpaper

hdmi_active=$(xrandr |grep ' connected' |grep 'HDMI' |awk '{print $1}')
if [ -n "$hdmi_active" ]; then
        bspc monitor HDMI-1 -d I II III IV V
        bspc monitor eDP-1 -d VI VII VIII IX X
else
        bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi

bspc config border_width              1
bspc config window_gap                10
bspc config split_ratio               0.50
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config remove_unplugged_monitors true
bspc focus_follows_pointer            true
bspc pointer_follows_monitor          true
bspc automatic_scheme                 spiral


bspc config normal_border_color       "#ECEFF4"
bspc config focused_border_color      "#88C0D0"
bspc config active_border_color       "#5E81AC"

bspc rule -a Alacritty desktop="^1" focus=on
bspc rule -a "Firefox Developer Edition" desktop='^2' focus=on
bspc rule -a Slack desktop="^3"
bspc rule -a Pcmanfm desktop='^4' focus=on
bspc rule -a Spotify desktop='^9' focus=on
bspc rule -a Stremio desktop='^8' focus=on
bspc rule -a TelegramDesktop desktop='^10' focus=on

bspc config external_rules_command "$(which p-in-p)"
